### PR TITLE
Updated resolution of images in document 

### PR DESCRIPTION
**Pull request by engrvip123**
Images added in info.md were not rendering properly in datasheet pdf document.

### CODE REVIEW

**Comment by urish** [comment]
Thanks, but please also deelete .vscode/settings.json from the pull request

**Comment by engrvip123** [comment]
> Thanks, but please also deelete .vscode/settings.json from the pull request

Where does this file lie? How to delete it.

**Comment by urish** [comment]
See under the "File changed" tab of the Pull Request:

image

**Comment by urish** [comment]
Thanks!

**Comment by engrvip123** [comment]
Why images are not visible in datasheet for my project? Earlier it was visible but after deleting .vscode/settings.json they are not.

**Comment by engrvip123** [comment]
What syntax could be used to change image dimensions in markdown so that appear properly in final datasheet pdf.

**Pull request merged**
